name: Bug Report
description: Report a documentation issue or error
title: '[Bug]: '
labels: ['bug', 'documentation']

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a documentation issue! This helps us improve the Butler Sheet Icons documentation for everyone.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of documentation issue are you reporting?
      options:
        - Incorrect information
        - Outdated content
        - Broken link or image
        - Missing documentation
        - Unclear instructions
        - Accessibility issue
        - Other
    validations:
      required: true

  - type: input
    id: page-url
    attributes:
      label: Page URL or Path
      description: Which page has the issue? (e.g., /guide/quick-start or full URL)
      placeholder: /guide/quick-start
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe the problem you found
      placeholder: The command shown in the example doesn't work as described...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should the documentation say or show instead?
      placeholder: The command should be... OR The documentation should explain...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information that might help?

  - type: dropdown
    id: browser
    attributes:
      label: Browser (if relevant)
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
        - Not applicable

  - type: checkboxes
    id: checks
    attributes:
      label: Verification
      description: Please confirm
      options:
        - label: I have searched existing issues for duplicates
          required: true
        - label: This is a documentation issue (not a Butler Sheet Icons tool issue)
          required: true